### ISSUE TITLE
No docs; no example; no tests = not simple

### ISSUE THREAD

**Issue by rreusser** [Bill4Time/simple-throttle#1]
:frowning:

**Comment by khous** [comment]
OK, there are actually fewer than 20 lines of code in this project, fewer still if you don't count the rjs boilerplate. I didn't make this for you, I made it for a project at bill4time. Fork it if you want to essentially test javascript's setTimeout function and add documentation superlative to what's included in the function declaration, but don't look a gift horse in the mouth for a project that should be codeable by anybody who understands why they might need a throttle.
